---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: clickhouse
  roles:
    - vector-role

- name: Install Lighthouse
  hosts: clickhouse
  roles:
    - lighthouse-role
